### ISSUE TITLE
Need completenes for GPIO_IN and GPIO_OUT

### ISSUE THREAD

**Issue by sumeetgadagkar** [zoroppz/baremetal_rpi#9]
https://github.com/zoroppz/baremetal_rpi/blob/0c5cacc2fe3d35efe223e7ed421d37dafa193909/drivers/inc/gpio.h#L40-L41

If we want to have GPIO_IN and GPIO_OUT we also need to have GPIO_ALT[0-5] and I feel that instead of a #define we should do a typedef enum.

**Comment by AashvijShenai** [comment]
> https://github.com/zoroppz/baremetal_rpi/blob/0c5cacc2fe3d35efe223e7ed421d37dafa193909/drivers/inc/gpio.h#L40-L41
> 
> If we want to have GPIO_IN and GPIO_OUT we also need to have GPIO_ALT[0-5] and I feel that instead of a #define we should do a typedef enum.

I initially thought input and output would be used more and hence defined them but as you state it, it feels off to have just to have these 2. Instead, I'll add a comment about the 8 values in the gpio.c and revert the definitions

**Comment by sumeetgadagkar** [comment]
Sounds good
